SUPPORTED_TYPES = [
    {"name": "integer", "type": "integer", "suffix": "int"},
    {"name": "integer(int8)", "type": "integer(int8)", "suffix": "i8"},
    {"name": "integer(int16)", "type": "integer(int16)", "suffix": "i16"},
    {"name": "integer(int32)", "type": "integer(int32)", "suffix": "i32"},
    {"name": "integer(int64)", "type": "integer(int64)", "suffix": "i64"},
    {"name": "integer(int128)", "type": "integer(int128)", "suffix": "i128"},
    {"name": "real", "type": "real", "suffix": "real"},
    {"name": "real(real32)", "type": "real(real32)", "suffix": "r32"},
    {"name": "real(real64)", "type": "real(real64)", "suffix": "r64"},
    {"name": "real(real128)", "type": "real(real128)", "suffix": "r128"},
    {"name": "real(8)", "type": "real(8)", "suffix": "r8"},
    {"name": "real(16)", "type": "real(16)", "suffix": "r16"},
    {"name": "logical", "type": "logical", "suffix": "log"},
    {"name": "complex", "type": "complex", "suffix": "cpx"},
    {"name": "complex(real64)", "type": "complex(real64)", "suffix": "c64"},
    {"name": "complex(real128)", "type": "complex(real128)", "suffix": "c128"},
]
